Single IP for all modules/services
simwir/P7-kode pull request #72
Opened 2019-12-05 14:38 UTC by Ekhao

2019-12-05 14:43 UTC, Zinoex requested changes

2019-12-05 14:43 UTC, Zinoex commented on robot/src/main.cpp
> +            options.time_addr = options.com_addr = options.pds_addr = options.order_addr options.robot_addr = address.first;
```suggestion
            options.time_addr = options.com_addr = options.pds_addr = options.order_addr = options.robot_addr = address.first;
```

2019-12-05 14:43 UTC, Zinoex approved these changes

2019-12-06 07:16 UTC, simwir approved these changes
Har en kommentar men er lidt :woman_shrugging:

2019-12-06 07:16 UTC, simwir commented on robot/src/main.cpp
> +        << "-a --single-ip <IP>[:<PORT>]     Set address of all modules and services.\n"
Det giver nok ikke så meget mening at kunne tage en port på denne da alt skal bruge forskellge porte.

2019-12-06 07:23 UTC, emilbaekdahl approved these changes

2019-12-06 07:38 UTC, Ekhao commented on robot/src/main.cpp
> +        << "-a --single-ip <IP>[:<PORT>]     Set address of all modules and services.\n"
Ja det er lidt dumt :upside_down_face:

2019-12-06 08:07 UTC, Hexxers approved these changes

2019-12-06 08:09 UTC, simwir requested changes

2019-12-06 08:09 UTC, simwir commented on robot/src/main.cpp
> +            options.time_addr = options.com_addr = options.pds_addr = options.order_addr = options.robot_addr = address.first;
```suggestion
            options.time_addr = options.com_addr = options.pds_addr = options.order_addr = options.robot_addr = std::string{optarg};
```

2019-12-06 08:09 UTC, simwir commented on robot/src/main.cpp
> +            address = parse_address(std::string{optarg})
```suggestion
```

2019-12-06 08:11 UTC, waefwerf commented on robot/src/main.cpp
> +                exit(1);
Ift future proofing tror jeg en bedre logik er bare at lade være at forbinde til en remote clock server, hvis systemtid er valgt, frem for at terminere. Det synes jeg godt -a må gøre.

2019-12-06 08:13 UTC, simwir approved these changes
Men ellers

2019-12-06 08:21 UTC, njulrik approved these changes

2019-12-06 08:22 UTC, merged